# Generated by Django 2.2.5 on 2019-11-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bath',
            new_name='baths',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cr',
        ),
    ]
