# Generated by Django 2.2.5 on 2019-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20191122_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=80),
        ),
    ]
