# Generated by Django 2.2.5 on 2019-11-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Accuracy',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Check_in',
            new_name='aommunication',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Cleanliness',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Communication',
            new_name='cleanliness',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Value',
            new_name='value',
        ),
    ]
