# Generated by Django 2.2.5 on 2019-11-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191113_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='aommunication',
            new_name='comunication',
        ),
    ]
