# Generated by Django 2.2.5 on 2019-11-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20191114_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comunication',
            new_name='communication',
        ),
    ]
